/*
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package marketcheck.cars.api.client.api;

import marketcheck.cars.api.client.ApiException;
import java.math.BigDecimal;
import marketcheck.cars.api..client.model.Error;
import marketcheck.cars.api..client.model.HistoricalListing;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for HistoryApi
 */
@Ignore
public class HistoryApiTest {

    private final HistoryApi api = new HistoryApi();

    
    /**
     * Get a cars online listing history
     *
     * The history API returns online listing history for a car identified by its VIN. History listings are sorted in the descending order of the listing date / last seen date
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void historyTest() throws ApiException {
        String vin = null;
        String apiKey = null;
        String fields = null;
        Integer rows = null;
        BigDecimal page = null;
        List<HistoricalListing> response = api.history(vin, apiKey, fields, rows, page);

        // TODO: test validations
    }
    
}
