/*
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package marketcheck.cars.api..client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import marketcheck.cars.api..client.model.Build;
import marketcheck.cars.api..client.model.Dealer;
import marketcheck.cars.api..client.model.ListingMedia;

/**
 * Minimal set of attributes describing a listing
 */
@ApiModel(description = "Minimal set of attributes describing a listing")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-03-09T10:14:35.317+05:30")
public class BaseListing {
  @SerializedName("id")
  private String id = null;

  @SerializedName("heading")
  private String heading = null;

  @SerializedName("vin")
  private String vin = null;

  @SerializedName("stock_no")
  private String stockNo = null;

  @SerializedName("price")
  private String price = null;

  @SerializedName("miles")
  private String miles = null;

  @SerializedName("inventory_type")
  private String inventoryType = null;

  @SerializedName("last_seen_at")
  private BigDecimal lastSeenAt = null;

  @SerializedName("last_seen_at_date")
  private String lastSeenAtDate = null;

  @SerializedName("scraped_at_date")
  private BigDecimal scrapedAtDate = null;

  @SerializedName("first_seen_at")
  private BigDecimal firstSeenAt = null;

  @SerializedName("first_seen_at_date")
  private String firstSeenAtDate = null;

  @SerializedName("ref_price")
  private String refPrice = null;

  @SerializedName("ref_miles")
  private String refMiles = null;

  @SerializedName("ref_price_dt")
  private Integer refPriceDt = null;

  @SerializedName("ref_miles_dt")
  private Integer refMilesDt = null;

  @SerializedName("dom")
  private BigDecimal dom = null;

  @SerializedName("dom_180")
  private BigDecimal dom180 = null;

  @SerializedName("dom_active")
  private BigDecimal domActive = null;

  @SerializedName("seller_type")
  private String sellerType = null;

  @SerializedName("exterior_color")
  private String exteriorColor = null;

  @SerializedName("interior_color")
  private String interiorColor = null;

  @SerializedName("vdp_url")
  private String vdpUrl = null;

  @SerializedName("source")
  private String source = null;

  @SerializedName("media")
  private ListingMedia media = null;

  @SerializedName("build")
  private Build build = null;

  @SerializedName("dealer")
  private Dealer dealer = null;

  @SerializedName("is_certified")
  private Integer isCertified = null;

  @SerializedName("distance")
  private BigDecimal distance = null;

  public BaseListing id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier representing a specific listing from the Marketcheck database
   * @return id
  **/
  @ApiModelProperty(value = "Unique identifier representing a specific listing from the Marketcheck database")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public BaseListing heading(String heading) {
    this.heading = heading;
    return this;
  }

   /**
   * Listing title as displayed on the source website
   * @return heading
  **/
  @ApiModelProperty(value = "Listing title as displayed on the source website")
  public String getHeading() {
    return heading;
  }

  public void setHeading(String heading) {
    this.heading = heading;
  }

  public BaseListing vin(String vin) {
    this.vin = vin;
    return this;
  }

   /**
   * VIN for the car
   * @return vin
  **/
  @ApiModelProperty(value = "VIN for the car")
  public String getVin() {
    return vin;
  }

  public void setVin(String vin) {
    this.vin = vin;
  }

  public BaseListing stockNo(String stockNo) {
    this.stockNo = stockNo;
    return this;
  }

   /**
   * Stock no of the car
   * @return stockNo
  **/
  @ApiModelProperty(value = "Stock no of the car")
  public String getStockNo() {
    return stockNo;
  }

  public void setStockNo(String stockNo) {
    this.stockNo = stockNo;
  }

  public BaseListing price(String price) {
    this.price = price;
    return this;
  }

   /**
   * Asking price for the car
   * @return price
  **/
  @ApiModelProperty(value = "Asking price for the car")
  public String getPrice() {
    return price;
  }

  public void setPrice(String price) {
    this.price = price;
  }

  public BaseListing miles(String miles) {
    this.miles = miles;
    return this;
  }

   /**
   * Odometer reading / reported miles usage for the car
   * @return miles
  **/
  @ApiModelProperty(value = "Odometer reading / reported miles usage for the car")
  public String getMiles() {
    return miles;
  }

  public void setMiles(String miles) {
    this.miles = miles;
  }

  public BaseListing inventoryType(String inventoryType) {
    this.inventoryType = inventoryType;
    return this;
  }

   /**
   * Inventory type of car
   * @return inventoryType
  **/
  @ApiModelProperty(value = "Inventory type of car")
  public String getInventoryType() {
    return inventoryType;
  }

  public void setInventoryType(String inventoryType) {
    this.inventoryType = inventoryType;
  }

  public BaseListing lastSeenAt(BigDecimal lastSeenAt) {
    this.lastSeenAt = lastSeenAt;
    return this;
  }

   /**
   * Listing last seen at (most recent) timestamp
   * @return lastSeenAt
  **/
  @ApiModelProperty(value = "Listing last seen at (most recent) timestamp")
  public BigDecimal getLastSeenAt() {
    return lastSeenAt;
  }

  public void setLastSeenAt(BigDecimal lastSeenAt) {
    this.lastSeenAt = lastSeenAt;
  }

  public BaseListing lastSeenAtDate(String lastSeenAtDate) {
    this.lastSeenAtDate = lastSeenAtDate;
    return this;
  }

   /**
   * Listing last seen at (most recent) date
   * @return lastSeenAtDate
  **/
  @ApiModelProperty(value = "Listing last seen at (most recent) date")
  public String getLastSeenAtDate() {
    return lastSeenAtDate;
  }

  public void setLastSeenAtDate(String lastSeenAtDate) {
    this.lastSeenAtDate = lastSeenAtDate;
  }

  public BaseListing scrapedAtDate(BigDecimal scrapedAtDate) {
    this.scrapedAtDate = scrapedAtDate;
    return this;
  }

   /**
   * Listing first seen at first scraped date
   * @return scrapedAtDate
  **/
  @ApiModelProperty(value = "Listing first seen at first scraped date")
  public BigDecimal getScrapedAtDate() {
    return scrapedAtDate;
  }

  public void setScrapedAtDate(BigDecimal scrapedAtDate) {
    this.scrapedAtDate = scrapedAtDate;
  }

  public BaseListing firstSeenAt(BigDecimal firstSeenAt) {
    this.firstSeenAt = firstSeenAt;
    return this;
  }

   /**
   * Listing first seen at first scraped timestamp
   * @return firstSeenAt
  **/
  @ApiModelProperty(value = "Listing first seen at first scraped timestamp")
  public BigDecimal getFirstSeenAt() {
    return firstSeenAt;
  }

  public void setFirstSeenAt(BigDecimal firstSeenAt) {
    this.firstSeenAt = firstSeenAt;
  }

  public BaseListing firstSeenAtDate(String firstSeenAtDate) {
    this.firstSeenAtDate = firstSeenAtDate;
    return this;
  }

   /**
   * Listing first seen at first scraped date
   * @return firstSeenAtDate
  **/
  @ApiModelProperty(value = "Listing first seen at first scraped date")
  public String getFirstSeenAtDate() {
    return firstSeenAtDate;
  }

  public void setFirstSeenAtDate(String firstSeenAtDate) {
    this.firstSeenAtDate = firstSeenAtDate;
  }

  public BaseListing refPrice(String refPrice) {
    this.refPrice = refPrice;
    return this;
  }

   /**
   * Last reported price for the car. If the asking price value is not or is available then the last_price could perhaps be used. last_price is the price for the car listed on the source website as of last_price_dt date
   * @return refPrice
  **/
  @ApiModelProperty(value = "Last reported price for the car. If the asking price value is not or is available then the last_price could perhaps be used. last_price is the price for the car listed on the source website as of last_price_dt date")
  public String getRefPrice() {
    return refPrice;
  }

  public void setRefPrice(String refPrice) {
    this.refPrice = refPrice;
  }

  public BaseListing refMiles(String refMiles) {
    this.refMiles = refMiles;
    return this;
  }

   /**
   * Last Odometer reading / reported miles usage for the car. If the asking miles value is not or is available then the last_miles could perhaps be used. last_miles is the miles for the car listed on the source website as of last_miles_dt date
   * @return refMiles
  **/
  @ApiModelProperty(value = "Last Odometer reading / reported miles usage for the car. If the asking miles value is not or is available then the last_miles could perhaps be used. last_miles is the miles for the car listed on the source website as of last_miles_dt date")
  public String getRefMiles() {
    return refMiles;
  }

  public void setRefMiles(String refMiles) {
    this.refMiles = refMiles;
  }

  public BaseListing refPriceDt(Integer refPriceDt) {
    this.refPriceDt = refPriceDt;
    return this;
  }

   /**
   * The date at which the last price was reported online. This is earlier to last_seen_date
   * @return refPriceDt
  **/
  @ApiModelProperty(value = "The date at which the last price was reported online. This is earlier to last_seen_date")
  public Integer getRefPriceDt() {
    return refPriceDt;
  }

  public void setRefPriceDt(Integer refPriceDt) {
    this.refPriceDt = refPriceDt;
  }

  public BaseListing refMilesDt(Integer refMilesDt) {
    this.refMilesDt = refMilesDt;
    return this;
  }

   /**
   * The date at which the last miles was reported online. This is earlier to last_seen_date
   * @return refMilesDt
  **/
  @ApiModelProperty(value = "The date at which the last miles was reported online. This is earlier to last_seen_date")
  public Integer getRefMilesDt() {
    return refMilesDt;
  }

  public void setRefMilesDt(Integer refMilesDt) {
    this.refMilesDt = refMilesDt;
  }

  public BaseListing dom(BigDecimal dom) {
    this.dom = dom;
    return this;
  }

   /**
   * Days on Market value for the car based on current and historical listings found in the Marketcheck database for this car
   * @return dom
  **/
  @ApiModelProperty(value = "Days on Market value for the car based on current and historical listings found in the Marketcheck database for this car")
  public BigDecimal getDom() {
    return dom;
  }

  public void setDom(BigDecimal dom) {
    this.dom = dom;
  }

  public BaseListing dom180(BigDecimal dom180) {
    this.dom180 = dom180;
    return this;
  }

   /**
   * Days on Market value for the car based on current and last 6 month listings found in the Marketcheck database for this car
   * @return dom180
  **/
  @ApiModelProperty(value = "Days on Market value for the car based on current and last 6 month listings found in the Marketcheck database for this car")
  public BigDecimal getDom180() {
    return dom180;
  }

  public void setDom180(BigDecimal dom180) {
    this.dom180 = dom180;
  }

  public BaseListing domActive(BigDecimal domActive) {
    this.domActive = domActive;
    return this;
  }

   /**
   * Days on Market value for the car based on current and last 30 days listings found in the Marketcheck database for this car
   * @return domActive
  **/
  @ApiModelProperty(value = "Days on Market value for the car based on current and last 30 days listings found in the Marketcheck database for this car")
  public BigDecimal getDomActive() {
    return domActive;
  }

  public void setDomActive(BigDecimal domActive) {
    this.domActive = domActive;
  }

  public BaseListing sellerType(String sellerType) {
    this.sellerType = sellerType;
    return this;
  }

   /**
   * Seller type for the car
   * @return sellerType
  **/
  @ApiModelProperty(value = "Seller type for the car")
  public String getSellerType() {
    return sellerType;
  }

  public void setSellerType(String sellerType) {
    this.sellerType = sellerType;
  }

  public BaseListing exteriorColor(String exteriorColor) {
    this.exteriorColor = exteriorColor;
    return this;
  }

   /**
   * Exterior color of the car
   * @return exteriorColor
  **/
  @ApiModelProperty(value = "Exterior color of the car")
  public String getExteriorColor() {
    return exteriorColor;
  }

  public void setExteriorColor(String exteriorColor) {
    this.exteriorColor = exteriorColor;
  }

  public BaseListing interiorColor(String interiorColor) {
    this.interiorColor = interiorColor;
    return this;
  }

   /**
   * Interior color of the car
   * @return interiorColor
  **/
  @ApiModelProperty(value = "Interior color of the car")
  public String getInteriorColor() {
    return interiorColor;
  }

  public void setInteriorColor(String interiorColor) {
    this.interiorColor = interiorColor;
  }

  public BaseListing vdpUrl(String vdpUrl) {
    this.vdpUrl = vdpUrl;
    return this;
  }

   /**
   * Vehicle Details Page url of the specific car
   * @return vdpUrl
  **/
  @ApiModelProperty(value = "Vehicle Details Page url of the specific car")
  public String getVdpUrl() {
    return vdpUrl;
  }

  public void setVdpUrl(String vdpUrl) {
    this.vdpUrl = vdpUrl;
  }

  public BaseListing source(String source) {
    this.source = source;
    return this;
  }

   /**
   * Source domain of the listing
   * @return source
  **/
  @ApiModelProperty(value = "Source domain of the listing")
  public String getSource() {
    return source;
  }

  public void setSource(String source) {
    this.source = source;
  }

  public BaseListing media(ListingMedia media) {
    this.media = media;
    return this;
  }

   /**
   * Car Media Attributes - main photo link/url and photo links
   * @return media
  **/
  @ApiModelProperty(value = "Car Media Attributes - main photo link/url and photo links")
  public ListingMedia getMedia() {
    return media;
  }

  public void setMedia(ListingMedia media) {
    this.media = media;
  }

  public BaseListing build(Build build) {
    this.build = build;
    return this;
  }

   /**
   * Get build
   * @return build
  **/
  @ApiModelProperty(value = "")
  public Build getBuild() {
    return build;
  }

  public void setBuild(Build build) {
    this.build = build;
  }

  public BaseListing dealer(Dealer dealer) {
    this.dealer = dealer;
    return this;
  }

   /**
   * Get dealer
   * @return dealer
  **/
  @ApiModelProperty(value = "")
  public Dealer getDealer() {
    return dealer;
  }

  public void setDealer(Dealer dealer) {
    this.dealer = dealer;
  }

  public BaseListing isCertified(Integer isCertified) {
    this.isCertified = isCertified;
    return this;
  }

   /**
   * Certified car
   * @return isCertified
  **/
  @ApiModelProperty(value = "Certified car")
  public Integer getIsCertified() {
    return isCertified;
  }

  public void setIsCertified(Integer isCertified) {
    this.isCertified = isCertified;
  }

  public BaseListing distance(BigDecimal distance) {
    this.distance = distance;
    return this;
  }

   /**
   * Distance of the car&#39;s location from the specified user lcoation
   * @return distance
  **/
  @ApiModelProperty(value = "Distance of the car's location from the specified user lcoation")
  public BigDecimal getDistance() {
    return distance;
  }

  public void setDistance(BigDecimal distance) {
    this.distance = distance;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BaseListing baseListing = (BaseListing) o;
    return Objects.equals(this.id, baseListing.id) &&
        Objects.equals(this.heading, baseListing.heading) &&
        Objects.equals(this.vin, baseListing.vin) &&
        Objects.equals(this.stockNo, baseListing.stockNo) &&
        Objects.equals(this.price, baseListing.price) &&
        Objects.equals(this.miles, baseListing.miles) &&
        Objects.equals(this.inventoryType, baseListing.inventoryType) &&
        Objects.equals(this.lastSeenAt, baseListing.lastSeenAt) &&
        Objects.equals(this.lastSeenAtDate, baseListing.lastSeenAtDate) &&
        Objects.equals(this.scrapedAtDate, baseListing.scrapedAtDate) &&
        Objects.equals(this.firstSeenAt, baseListing.firstSeenAt) &&
        Objects.equals(this.firstSeenAtDate, baseListing.firstSeenAtDate) &&
        Objects.equals(this.refPrice, baseListing.refPrice) &&
        Objects.equals(this.refMiles, baseListing.refMiles) &&
        Objects.equals(this.refPriceDt, baseListing.refPriceDt) &&
        Objects.equals(this.refMilesDt, baseListing.refMilesDt) &&
        Objects.equals(this.dom, baseListing.dom) &&
        Objects.equals(this.dom180, baseListing.dom180) &&
        Objects.equals(this.domActive, baseListing.domActive) &&
        Objects.equals(this.sellerType, baseListing.sellerType) &&
        Objects.equals(this.exteriorColor, baseListing.exteriorColor) &&
        Objects.equals(this.interiorColor, baseListing.interiorColor) &&
        Objects.equals(this.vdpUrl, baseListing.vdpUrl) &&
        Objects.equals(this.source, baseListing.source) &&
        Objects.equals(this.media, baseListing.media) &&
        Objects.equals(this.build, baseListing.build) &&
        Objects.equals(this.dealer, baseListing.dealer) &&
        Objects.equals(this.isCertified, baseListing.isCertified) &&
        Objects.equals(this.distance, baseListing.distance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, heading, vin, stockNo, price, miles, inventoryType, lastSeenAt, lastSeenAtDate, scrapedAtDate, firstSeenAt, firstSeenAtDate, refPrice, refMiles, refPriceDt, refMilesDt, dom, dom180, domActive, sellerType, exteriorColor, interiorColor, vdpUrl, source, media, build, dealer, isCertified, distance);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BaseListing {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    heading: ").append(toIndentedString(heading)).append("\n");
    sb.append("    vin: ").append(toIndentedString(vin)).append("\n");
    sb.append("    stockNo: ").append(toIndentedString(stockNo)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    miles: ").append(toIndentedString(miles)).append("\n");
    sb.append("    inventoryType: ").append(toIndentedString(inventoryType)).append("\n");
    sb.append("    lastSeenAt: ").append(toIndentedString(lastSeenAt)).append("\n");
    sb.append("    lastSeenAtDate: ").append(toIndentedString(lastSeenAtDate)).append("\n");
    sb.append("    scrapedAtDate: ").append(toIndentedString(scrapedAtDate)).append("\n");
    sb.append("    firstSeenAt: ").append(toIndentedString(firstSeenAt)).append("\n");
    sb.append("    firstSeenAtDate: ").append(toIndentedString(firstSeenAtDate)).append("\n");
    sb.append("    refPrice: ").append(toIndentedString(refPrice)).append("\n");
    sb.append("    refMiles: ").append(toIndentedString(refMiles)).append("\n");
    sb.append("    refPriceDt: ").append(toIndentedString(refPriceDt)).append("\n");
    sb.append("    refMilesDt: ").append(toIndentedString(refMilesDt)).append("\n");
    sb.append("    dom: ").append(toIndentedString(dom)).append("\n");
    sb.append("    dom180: ").append(toIndentedString(dom180)).append("\n");
    sb.append("    domActive: ").append(toIndentedString(domActive)).append("\n");
    sb.append("    sellerType: ").append(toIndentedString(sellerType)).append("\n");
    sb.append("    exteriorColor: ").append(toIndentedString(exteriorColor)).append("\n");
    sb.append("    interiorColor: ").append(toIndentedString(interiorColor)).append("\n");
    sb.append("    vdpUrl: ").append(toIndentedString(vdpUrl)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    media: ").append(toIndentedString(media)).append("\n");
    sb.append("    build: ").append(toIndentedString(build)).append("\n");
    sb.append("    dealer: ").append(toIndentedString(dealer)).append("\n");
    sb.append("    isCertified: ").append(toIndentedString(isCertified)).append("\n");
    sb.append("    distance: ").append(toIndentedString(distance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

