/*
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package marketcheck.cars.api..client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * CompetitorsSimilarCars
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-03-09T10:14:35.317+05:30")
public class CompetitorsSimilarCars {
  @SerializedName("name")
  private String name = null;

  @SerializedName("avg_price")
  private BigDecimal avgPrice = null;

  @SerializedName("avg_miles")
  private BigDecimal avgMiles = null;

  @SerializedName("avg_market_value")
  private BigDecimal avgMarketValue = null;

  public CompetitorsSimilarCars name(String name) {
    this.name = name;
    return this;
  }

   /**
   * ymm_comb_name
   * @return name
  **/
  @ApiModelProperty(value = "ymm_comb_name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CompetitorsSimilarCars avgPrice(BigDecimal avgPrice) {
    this.avgPrice = avgPrice;
    return this;
  }

   /**
   * Average price of year make model combination
   * @return avgPrice
  **/
  @ApiModelProperty(value = "Average price of year make model combination")
  public BigDecimal getAvgPrice() {
    return avgPrice;
  }

  public void setAvgPrice(BigDecimal avgPrice) {
    this.avgPrice = avgPrice;
  }

  public CompetitorsSimilarCars avgMiles(BigDecimal avgMiles) {
    this.avgMiles = avgMiles;
    return this;
  }

   /**
   * Average mileage of year make model combination
   * @return avgMiles
  **/
  @ApiModelProperty(value = "Average mileage of year make model combination")
  public BigDecimal getAvgMiles() {
    return avgMiles;
  }

  public void setAvgMiles(BigDecimal avgMiles) {
    this.avgMiles = avgMiles;
  }

  public CompetitorsSimilarCars avgMarketValue(BigDecimal avgMarketValue) {
    this.avgMarketValue = avgMarketValue;
    return this;
  }

   /**
   * Average market value of year make model combination
   * @return avgMarketValue
  **/
  @ApiModelProperty(value = "Average market value of year make model combination")
  public BigDecimal getAvgMarketValue() {
    return avgMarketValue;
  }

  public void setAvgMarketValue(BigDecimal avgMarketValue) {
    this.avgMarketValue = avgMarketValue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompetitorsSimilarCars competitorsSimilarCars = (CompetitorsSimilarCars) o;
    return Objects.equals(this.name, competitorsSimilarCars.name) &&
        Objects.equals(this.avgPrice, competitorsSimilarCars.avgPrice) &&
        Objects.equals(this.avgMiles, competitorsSimilarCars.avgMiles) &&
        Objects.equals(this.avgMarketValue, competitorsSimilarCars.avgMarketValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, avgPrice, avgMiles, avgMarketValue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompetitorsSimilarCars {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    avgPrice: ").append(toIndentedString(avgPrice)).append("\n");
    sb.append("    avgMiles: ").append(toIndentedString(avgMiles)).append("\n");
    sb.append("    avgMarketValue: ").append(toIndentedString(avgMarketValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

