/*
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package marketcheck.cars.api..client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import marketcheck.cars.api..client.model.CompetitorsCarDetails;
import marketcheck.cars.api..client.model.CompetitorsSameCars;
import marketcheck.cars.api..client.model.CompetitorsSimilarCars;

/**
 * CompetitorsPoint
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-03-09T10:14:35.317+05:30")
public class CompetitorsPoint {
  @SerializedName("current_car")
  private CompetitorsCarDetails currentCar = null;

  @SerializedName("similar_car_models")
  private List<CompetitorsSimilarCars> similarCarModels = null;

  @SerializedName("same_car_models")
  private List<CompetitorsSameCars> sameCarModels = null;

  public CompetitorsPoint currentCar(CompetitorsCarDetails currentCar) {
    this.currentCar = currentCar;
    return this;
  }

   /**
   * Details of current car
   * @return currentCar
  **/
  @ApiModelProperty(value = "Details of current car")
  public CompetitorsCarDetails getCurrentCar() {
    return currentCar;
  }

  public void setCurrentCar(CompetitorsCarDetails currentCar) {
    this.currentCar = currentCar;
  }

  public CompetitorsPoint similarCarModels(List<CompetitorsSimilarCars> similarCarModels) {
    this.similarCarModels = similarCarModels;
    return this;
  }

  public CompetitorsPoint addSimilarCarModelsItem(CompetitorsSimilarCars similarCarModelsItem) {
    if (this.similarCarModels == null) {
      this.similarCarModels = new ArrayList<CompetitorsSimilarCars>();
    }
    this.similarCarModels.add(similarCarModelsItem);
    return this;
  }

   /**
   * Get similarCarModels
   * @return similarCarModels
  **/
  @ApiModelProperty(value = "")
  public List<CompetitorsSimilarCars> getSimilarCarModels() {
    return similarCarModels;
  }

  public void setSimilarCarModels(List<CompetitorsSimilarCars> similarCarModels) {
    this.similarCarModels = similarCarModels;
  }

  public CompetitorsPoint sameCarModels(List<CompetitorsSameCars> sameCarModels) {
    this.sameCarModels = sameCarModels;
    return this;
  }

  public CompetitorsPoint addSameCarModelsItem(CompetitorsSameCars sameCarModelsItem) {
    if (this.sameCarModels == null) {
      this.sameCarModels = new ArrayList<CompetitorsSameCars>();
    }
    this.sameCarModels.add(sameCarModelsItem);
    return this;
  }

   /**
   * Get sameCarModels
   * @return sameCarModels
  **/
  @ApiModelProperty(value = "")
  public List<CompetitorsSameCars> getSameCarModels() {
    return sameCarModels;
  }

  public void setSameCarModels(List<CompetitorsSameCars> sameCarModels) {
    this.sameCarModels = sameCarModels;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompetitorsPoint competitorsPoint = (CompetitorsPoint) o;
    return Objects.equals(this.currentCar, competitorsPoint.currentCar) &&
        Objects.equals(this.similarCarModels, competitorsPoint.similarCarModels) &&
        Objects.equals(this.sameCarModels, competitorsPoint.sameCarModels);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currentCar, similarCarModels, sameCarModels);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompetitorsPoint {\n");
    
    sb.append("    currentCar: ").append(toIndentedString(currentCar)).append("\n");
    sb.append("    similarCarModels: ").append(toIndentedString(similarCarModels)).append("\n");
    sb.append("    sameCarModels: ").append(toIndentedString(sameCarModels)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

