/*
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package marketcheck.cars.api..client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * DepreciationStats
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-03-09T10:14:35.317+05:30")
public class DepreciationStats {
  @SerializedName("name")
  private String name = null;

  @SerializedName("current_value")
  private BigDecimal currentValue = null;

  @SerializedName("one_year_from_now")
  private BigDecimal oneYearFromNow = null;

  @SerializedName("one_year_from_now_percent")
  private BigDecimal oneYearFromNowPercent = null;

  @SerializedName("two_year_from_now")
  private BigDecimal twoYearFromNow = null;

  @SerializedName("two_year_from_now_percent")
  private BigDecimal twoYearFromNowPercent = null;

  @SerializedName("five_year_from_now")
  private BigDecimal fiveYearFromNow = null;

  @SerializedName("five_year_from_now_percent")
  private BigDecimal fiveYearFromNowPercent = null;

  public DepreciationStats name(String name) {
    this.name = name;
    return this;
  }

   /**
   * ymm_comb_name
   * @return name
  **/
  @ApiModelProperty(value = "ymm_comb_name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public DepreciationStats currentValue(BigDecimal currentValue) {
    this.currentValue = currentValue;
    return this;
  }

   /**
   * Price of year make model combination
   * @return currentValue
  **/
  @ApiModelProperty(value = "Price of year make model combination")
  public BigDecimal getCurrentValue() {
    return currentValue;
  }

  public void setCurrentValue(BigDecimal currentValue) {
    this.currentValue = currentValue;
  }

  public DepreciationStats oneYearFromNow(BigDecimal oneYearFromNow) {
    this.oneYearFromNow = oneYearFromNow;
    return this;
  }

   /**
   * price after one year from now
   * @return oneYearFromNow
  **/
  @ApiModelProperty(value = "price after one year from now")
  public BigDecimal getOneYearFromNow() {
    return oneYearFromNow;
  }

  public void setOneYearFromNow(BigDecimal oneYearFromNow) {
    this.oneYearFromNow = oneYearFromNow;
  }

  public DepreciationStats oneYearFromNowPercent(BigDecimal oneYearFromNowPercent) {
    this.oneYearFromNowPercent = oneYearFromNowPercent;
    return this;
  }

   /**
   * price depreciation percent after one year from now
   * @return oneYearFromNowPercent
  **/
  @ApiModelProperty(value = "price depreciation percent after one year from now")
  public BigDecimal getOneYearFromNowPercent() {
    return oneYearFromNowPercent;
  }

  public void setOneYearFromNowPercent(BigDecimal oneYearFromNowPercent) {
    this.oneYearFromNowPercent = oneYearFromNowPercent;
  }

  public DepreciationStats twoYearFromNow(BigDecimal twoYearFromNow) {
    this.twoYearFromNow = twoYearFromNow;
    return this;
  }

   /**
   * price after two year from now
   * @return twoYearFromNow
  **/
  @ApiModelProperty(value = "price after two year from now")
  public BigDecimal getTwoYearFromNow() {
    return twoYearFromNow;
  }

  public void setTwoYearFromNow(BigDecimal twoYearFromNow) {
    this.twoYearFromNow = twoYearFromNow;
  }

  public DepreciationStats twoYearFromNowPercent(BigDecimal twoYearFromNowPercent) {
    this.twoYearFromNowPercent = twoYearFromNowPercent;
    return this;
  }

   /**
   * price depreciation percent after two year from now
   * @return twoYearFromNowPercent
  **/
  @ApiModelProperty(value = "price depreciation percent after two year from now")
  public BigDecimal getTwoYearFromNowPercent() {
    return twoYearFromNowPercent;
  }

  public void setTwoYearFromNowPercent(BigDecimal twoYearFromNowPercent) {
    this.twoYearFromNowPercent = twoYearFromNowPercent;
  }

  public DepreciationStats fiveYearFromNow(BigDecimal fiveYearFromNow) {
    this.fiveYearFromNow = fiveYearFromNow;
    return this;
  }

   /**
   * price after five year from now
   * @return fiveYearFromNow
  **/
  @ApiModelProperty(value = "price after five year from now")
  public BigDecimal getFiveYearFromNow() {
    return fiveYearFromNow;
  }

  public void setFiveYearFromNow(BigDecimal fiveYearFromNow) {
    this.fiveYearFromNow = fiveYearFromNow;
  }

  public DepreciationStats fiveYearFromNowPercent(BigDecimal fiveYearFromNowPercent) {
    this.fiveYearFromNowPercent = fiveYearFromNowPercent;
    return this;
  }

   /**
   * price depreciation percent after five year from now
   * @return fiveYearFromNowPercent
  **/
  @ApiModelProperty(value = "price depreciation percent after five year from now")
  public BigDecimal getFiveYearFromNowPercent() {
    return fiveYearFromNowPercent;
  }

  public void setFiveYearFromNowPercent(BigDecimal fiveYearFromNowPercent) {
    this.fiveYearFromNowPercent = fiveYearFromNowPercent;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DepreciationStats depreciationStats = (DepreciationStats) o;
    return Objects.equals(this.name, depreciationStats.name) &&
        Objects.equals(this.currentValue, depreciationStats.currentValue) &&
        Objects.equals(this.oneYearFromNow, depreciationStats.oneYearFromNow) &&
        Objects.equals(this.oneYearFromNowPercent, depreciationStats.oneYearFromNowPercent) &&
        Objects.equals(this.twoYearFromNow, depreciationStats.twoYearFromNow) &&
        Objects.equals(this.twoYearFromNowPercent, depreciationStats.twoYearFromNowPercent) &&
        Objects.equals(this.fiveYearFromNow, depreciationStats.fiveYearFromNow) &&
        Objects.equals(this.fiveYearFromNowPercent, depreciationStats.fiveYearFromNowPercent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, currentValue, oneYearFromNow, oneYearFromNowPercent, twoYearFromNow, twoYearFromNowPercent, fiveYearFromNow, fiveYearFromNowPercent);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DepreciationStats {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    currentValue: ").append(toIndentedString(currentValue)).append("\n");
    sb.append("    oneYearFromNow: ").append(toIndentedString(oneYearFromNow)).append("\n");
    sb.append("    oneYearFromNowPercent: ").append(toIndentedString(oneYearFromNowPercent)).append("\n");
    sb.append("    twoYearFromNow: ").append(toIndentedString(twoYearFromNow)).append("\n");
    sb.append("    twoYearFromNowPercent: ").append(toIndentedString(twoYearFromNowPercent)).append("\n");
    sb.append("    fiveYearFromNow: ").append(toIndentedString(fiveYearFromNow)).append("\n");
    sb.append("    fiveYearFromNowPercent: ").append(toIndentedString(fiveYearFromNowPercent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

