/*
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package marketcheck.cars.api..client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ListingExtraAttributes
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-03-09T10:14:35.317+05:30")
public class ListingExtraAttributes {
  @SerializedName("options")
  private List<String> options = null;

  @SerializedName("features")
  private List<String> features = null;

  @SerializedName("seller_comment")
  private String sellerComment = null;

  public ListingExtraAttributes options(List<String> options) {
    this.options = options;
    return this;
  }

  public ListingExtraAttributes addOptionsItem(String optionsItem) {
    if (this.options == null) {
      this.options = new ArrayList<String>();
    }
    this.options.add(optionsItem);
    return this;
  }

   /**
   * Installed Options of the car
   * @return options
  **/
  @ApiModelProperty(value = "Installed Options of the car")
  public List<String> getOptions() {
    return options;
  }

  public void setOptions(List<String> options) {
    this.options = options;
  }

  public ListingExtraAttributes features(List<String> features) {
    this.features = features;
    return this;
  }

  public ListingExtraAttributes addFeaturesItem(String featuresItem) {
    if (this.features == null) {
      this.features = new ArrayList<String>();
    }
    this.features.add(featuresItem);
    return this;
  }

   /**
   * List of Features available with the car
   * @return features
  **/
  @ApiModelProperty(value = "List of Features available with the car")
  public List<String> getFeatures() {
    return features;
  }

  public void setFeatures(List<String> features) {
    this.features = features;
  }

  public ListingExtraAttributes sellerComment(String sellerComment) {
    this.sellerComment = sellerComment;
    return this;
  }

   /**
   * Seller comment for the car
   * @return sellerComment
  **/
  @ApiModelProperty(value = "Seller comment for the car")
  public String getSellerComment() {
    return sellerComment;
  }

  public void setSellerComment(String sellerComment) {
    this.sellerComment = sellerComment;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListingExtraAttributes listingExtraAttributes = (ListingExtraAttributes) o;
    return Objects.equals(this.options, listingExtraAttributes.options) &&
        Objects.equals(this.features, listingExtraAttributes.features) &&
        Objects.equals(this.sellerComment, listingExtraAttributes.sellerComment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(options, features, sellerComment);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListingExtraAttributes {\n");
    
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("    features: ").append(toIndentedString(features)).append("\n");
    sb.append("    sellerComment: ").append(toIndentedString(sellerComment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

