/*
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package marketcheck.cars.api..client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import marketcheck.cars.api..client.model.Build;
import marketcheck.cars.api..client.model.Dealer;
import marketcheck.cars.api..client.model.ListingExtraAttributes;
import marketcheck.cars.api..client.model.ListingMedia;
import marketcheck.cars.api..client.model.Location;

/**
 * Represents a full list of attributes available with Marketcheck for a car
 */
@ApiModel(description = "Represents a full list of attributes available with Marketcheck for a car")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-03-09T10:14:35.317+05:30")
public class Listing {
  @SerializedName("id")
  private String id = null;

  @SerializedName("heading")
  private String heading = null;

  @SerializedName("vin")
  private String vin = null;

  @SerializedName("stock_no")
  private String stockNo = null;

  @SerializedName("price")
  private String price = null;

  @SerializedName("msrp")
  private String msrp = null;

  @SerializedName("miles")
  private String miles = null;

  @SerializedName("inventory_type")
  private String inventoryType = null;

  @SerializedName("scraped_at_date")
  private BigDecimal scrapedAtDate = null;

  @SerializedName("first_seen_at")
  private BigDecimal firstSeenAt = null;

  @SerializedName("first_seen_at_date")
  private String firstSeenAtDate = null;

  @SerializedName("vdp_url")
  private String vdpUrl = null;

  @SerializedName("source")
  private String source = null;

  @SerializedName("is_certified")
  private Integer isCertified = null;

  @SerializedName("dom")
  private BigDecimal dom = null;

  @SerializedName("dom_180")
  private BigDecimal dom180 = null;

  @SerializedName("dom_active")
  private BigDecimal domActive = null;

  @SerializedName("seller_type")
  private String sellerType = null;

  @SerializedName("last_seen_at")
  private BigDecimal lastSeenAt = null;

  @SerializedName("last_seen_at_date")
  private String lastSeenAtDate = null;

  @SerializedName("build")
  private Build build = null;

  @SerializedName("media")
  private ListingMedia media = null;

  @SerializedName("extra")
  private ListingExtraAttributes extra = null;

  @SerializedName("dealer")
  private Dealer dealer = null;

  @SerializedName("car_location")
  private Location carLocation = null;

  public Listing id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier representing a specific listing from the Marketcheck database
   * @return id
  **/
  @ApiModelProperty(value = "Unique identifier representing a specific listing from the Marketcheck database")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Listing heading(String heading) {
    this.heading = heading;
    return this;
  }

   /**
   * Listing heading
   * @return heading
  **/
  @ApiModelProperty(value = "Listing heading")
  public String getHeading() {
    return heading;
  }

  public void setHeading(String heading) {
    this.heading = heading;
  }

  public Listing vin(String vin) {
    this.vin = vin;
    return this;
  }

   /**
   * VIN for the car
   * @return vin
  **/
  @ApiModelProperty(value = "VIN for the car")
  public String getVin() {
    return vin;
  }

  public void setVin(String vin) {
    this.vin = vin;
  }

  public Listing stockNo(String stockNo) {
    this.stockNo = stockNo;
    return this;
  }

   /**
   * Stock no of the car
   * @return stockNo
  **/
  @ApiModelProperty(value = "Stock no of the car")
  public String getStockNo() {
    return stockNo;
  }

  public void setStockNo(String stockNo) {
    this.stockNo = stockNo;
  }

  public Listing price(String price) {
    this.price = price;
    return this;
  }

   /**
   * Asking price for the car
   * @return price
  **/
  @ApiModelProperty(value = "Asking price for the car")
  public String getPrice() {
    return price;
  }

  public void setPrice(String price) {
    this.price = price;
  }

  public Listing msrp(String msrp) {
    this.msrp = msrp;
    return this;
  }

   /**
   * MSRP for the car
   * @return msrp
  **/
  @ApiModelProperty(value = "MSRP for the car")
  public String getMsrp() {
    return msrp;
  }

  public void setMsrp(String msrp) {
    this.msrp = msrp;
  }

  public Listing miles(String miles) {
    this.miles = miles;
    return this;
  }

   /**
   * Odometer reading / reported miles usage for the car
   * @return miles
  **/
  @ApiModelProperty(value = "Odometer reading / reported miles usage for the car")
  public String getMiles() {
    return miles;
  }

  public void setMiles(String miles) {
    this.miles = miles;
  }

  public Listing inventoryType(String inventoryType) {
    this.inventoryType = inventoryType;
    return this;
  }

   /**
   * Inventory type of car
   * @return inventoryType
  **/
  @ApiModelProperty(value = "Inventory type of car")
  public String getInventoryType() {
    return inventoryType;
  }

  public void setInventoryType(String inventoryType) {
    this.inventoryType = inventoryType;
  }

  public Listing scrapedAtDate(BigDecimal scrapedAtDate) {
    this.scrapedAtDate = scrapedAtDate;
    return this;
  }

   /**
   * Listing first seen at first scraped date
   * @return scrapedAtDate
  **/
  @ApiModelProperty(value = "Listing first seen at first scraped date")
  public BigDecimal getScrapedAtDate() {
    return scrapedAtDate;
  }

  public void setScrapedAtDate(BigDecimal scrapedAtDate) {
    this.scrapedAtDate = scrapedAtDate;
  }

  public Listing firstSeenAt(BigDecimal firstSeenAt) {
    this.firstSeenAt = firstSeenAt;
    return this;
  }

   /**
   * Listing first seen at first scraped timestamp
   * @return firstSeenAt
  **/
  @ApiModelProperty(value = "Listing first seen at first scraped timestamp")
  public BigDecimal getFirstSeenAt() {
    return firstSeenAt;
  }

  public void setFirstSeenAt(BigDecimal firstSeenAt) {
    this.firstSeenAt = firstSeenAt;
  }

  public Listing firstSeenAtDate(String firstSeenAtDate) {
    this.firstSeenAtDate = firstSeenAtDate;
    return this;
  }

   /**
   * Listing first seen at first scraped date
   * @return firstSeenAtDate
  **/
  @ApiModelProperty(value = "Listing first seen at first scraped date")
  public String getFirstSeenAtDate() {
    return firstSeenAtDate;
  }

  public void setFirstSeenAtDate(String firstSeenAtDate) {
    this.firstSeenAtDate = firstSeenAtDate;
  }

  public Listing vdpUrl(String vdpUrl) {
    this.vdpUrl = vdpUrl;
    return this;
  }

   /**
   * Vehicle Details Page url of the specific car
   * @return vdpUrl
  **/
  @ApiModelProperty(value = "Vehicle Details Page url of the specific car")
  public String getVdpUrl() {
    return vdpUrl;
  }

  public void setVdpUrl(String vdpUrl) {
    this.vdpUrl = vdpUrl;
  }

  public Listing source(String source) {
    this.source = source;
    return this;
  }

   /**
   * Source domain of the listing
   * @return source
  **/
  @ApiModelProperty(value = "Source domain of the listing")
  public String getSource() {
    return source;
  }

  public void setSource(String source) {
    this.source = source;
  }

  public Listing isCertified(Integer isCertified) {
    this.isCertified = isCertified;
    return this;
  }

   /**
   * Flag indicating whether the car is Certified
   * @return isCertified
  **/
  @ApiModelProperty(value = "Flag indicating whether the car is Certified")
  public Integer getIsCertified() {
    return isCertified;
  }

  public void setIsCertified(Integer isCertified) {
    this.isCertified = isCertified;
  }

  public Listing dom(BigDecimal dom) {
    this.dom = dom;
    return this;
  }

   /**
   * Days on Market value for the car based on current and historical listings found in the Marketcheck database for this car
   * @return dom
  **/
  @ApiModelProperty(value = "Days on Market value for the car based on current and historical listings found in the Marketcheck database for this car")
  public BigDecimal getDom() {
    return dom;
  }

  public void setDom(BigDecimal dom) {
    this.dom = dom;
  }

  public Listing dom180(BigDecimal dom180) {
    this.dom180 = dom180;
    return this;
  }

   /**
   * Days on Market value for the car based on current and last 6 month listings found in the Marketcheck database for this car
   * @return dom180
  **/
  @ApiModelProperty(value = "Days on Market value for the car based on current and last 6 month listings found in the Marketcheck database for this car")
  public BigDecimal getDom180() {
    return dom180;
  }

  public void setDom180(BigDecimal dom180) {
    this.dom180 = dom180;
  }

  public Listing domActive(BigDecimal domActive) {
    this.domActive = domActive;
    return this;
  }

   /**
   * Days on Market value for the car based on current and last 30 days listings found in the Marketcheck database for this car
   * @return domActive
  **/
  @ApiModelProperty(value = "Days on Market value for the car based on current and last 30 days listings found in the Marketcheck database for this car")
  public BigDecimal getDomActive() {
    return domActive;
  }

  public void setDomActive(BigDecimal domActive) {
    this.domActive = domActive;
  }

  public Listing sellerType(String sellerType) {
    this.sellerType = sellerType;
    return this;
  }

   /**
   * Seller type for the car
   * @return sellerType
  **/
  @ApiModelProperty(value = "Seller type for the car")
  public String getSellerType() {
    return sellerType;
  }

  public void setSellerType(String sellerType) {
    this.sellerType = sellerType;
  }

  public Listing lastSeenAt(BigDecimal lastSeenAt) {
    this.lastSeenAt = lastSeenAt;
    return this;
  }

   /**
   * Listing last seen at (most recent) timestamp
   * @return lastSeenAt
  **/
  @ApiModelProperty(value = "Listing last seen at (most recent) timestamp")
  public BigDecimal getLastSeenAt() {
    return lastSeenAt;
  }

  public void setLastSeenAt(BigDecimal lastSeenAt) {
    this.lastSeenAt = lastSeenAt;
  }

  public Listing lastSeenAtDate(String lastSeenAtDate) {
    this.lastSeenAtDate = lastSeenAtDate;
    return this;
  }

   /**
   * Listing last seen at (most recent) date
   * @return lastSeenAtDate
  **/
  @ApiModelProperty(value = "Listing last seen at (most recent) date")
  public String getLastSeenAtDate() {
    return lastSeenAtDate;
  }

  public void setLastSeenAtDate(String lastSeenAtDate) {
    this.lastSeenAtDate = lastSeenAtDate;
  }

  public Listing build(Build build) {
    this.build = build;
    return this;
  }

   /**
   * Build / Specifications attributes
   * @return build
  **/
  @ApiModelProperty(value = "Build / Specifications attributes")
  public Build getBuild() {
    return build;
  }

  public void setBuild(Build build) {
    this.build = build;
  }

  public Listing media(ListingMedia media) {
    this.media = media;
    return this;
  }

   /**
   * Car Media Attributes - main photo link/url and photo links
   * @return media
  **/
  @ApiModelProperty(value = "Car Media Attributes - main photo link/url and photo links")
  public ListingMedia getMedia() {
    return media;
  }

  public void setMedia(ListingMedia media) {
    this.media = media;
  }

  public Listing extra(ListingExtraAttributes extra) {
    this.extra = extra;
    return this;
  }

   /**
   * Extra attributes for the listing - options, features, seller comments etc
   * @return extra
  **/
  @ApiModelProperty(value = "Extra attributes for the listing - options, features, seller comments etc")
  public ListingExtraAttributes getExtra() {
    return extra;
  }

  public void setExtra(ListingExtraAttributes extra) {
    this.extra = extra;
  }

  public Listing dealer(Dealer dealer) {
    this.dealer = dealer;
    return this;
  }

   /**
   * Get dealer
   * @return dealer
  **/
  @ApiModelProperty(value = "")
  public Dealer getDealer() {
    return dealer;
  }

  public void setDealer(Dealer dealer) {
    this.dealer = dealer;
  }

  public Listing carLocation(Location carLocation) {
    this.carLocation = carLocation;
    return this;
  }

   /**
   * Car location data. Included only if its a different location to the dealers location
   * @return carLocation
  **/
  @ApiModelProperty(value = "Car location data. Included only if its a different location to the dealers location")
  public Location getCarLocation() {
    return carLocation;
  }

  public void setCarLocation(Location carLocation) {
    this.carLocation = carLocation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Listing listing = (Listing) o;
    return Objects.equals(this.id, listing.id) &&
        Objects.equals(this.heading, listing.heading) &&
        Objects.equals(this.vin, listing.vin) &&
        Objects.equals(this.stockNo, listing.stockNo) &&
        Objects.equals(this.price, listing.price) &&
        Objects.equals(this.msrp, listing.msrp) &&
        Objects.equals(this.miles, listing.miles) &&
        Objects.equals(this.inventoryType, listing.inventoryType) &&
        Objects.equals(this.scrapedAtDate, listing.scrapedAtDate) &&
        Objects.equals(this.firstSeenAt, listing.firstSeenAt) &&
        Objects.equals(this.firstSeenAtDate, listing.firstSeenAtDate) &&
        Objects.equals(this.vdpUrl, listing.vdpUrl) &&
        Objects.equals(this.source, listing.source) &&
        Objects.equals(this.isCertified, listing.isCertified) &&
        Objects.equals(this.dom, listing.dom) &&
        Objects.equals(this.dom180, listing.dom180) &&
        Objects.equals(this.domActive, listing.domActive) &&
        Objects.equals(this.sellerType, listing.sellerType) &&
        Objects.equals(this.lastSeenAt, listing.lastSeenAt) &&
        Objects.equals(this.lastSeenAtDate, listing.lastSeenAtDate) &&
        Objects.equals(this.build, listing.build) &&
        Objects.equals(this.media, listing.media) &&
        Objects.equals(this.extra, listing.extra) &&
        Objects.equals(this.dealer, listing.dealer) &&
        Objects.equals(this.carLocation, listing.carLocation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, heading, vin, stockNo, price, msrp, miles, inventoryType, scrapedAtDate, firstSeenAt, firstSeenAtDate, vdpUrl, source, isCertified, dom, dom180, domActive, sellerType, lastSeenAt, lastSeenAtDate, build, media, extra, dealer, carLocation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Listing {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    heading: ").append(toIndentedString(heading)).append("\n");
    sb.append("    vin: ").append(toIndentedString(vin)).append("\n");
    sb.append("    stockNo: ").append(toIndentedString(stockNo)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    msrp: ").append(toIndentedString(msrp)).append("\n");
    sb.append("    miles: ").append(toIndentedString(miles)).append("\n");
    sb.append("    inventoryType: ").append(toIndentedString(inventoryType)).append("\n");
    sb.append("    scrapedAtDate: ").append(toIndentedString(scrapedAtDate)).append("\n");
    sb.append("    firstSeenAt: ").append(toIndentedString(firstSeenAt)).append("\n");
    sb.append("    firstSeenAtDate: ").append(toIndentedString(firstSeenAtDate)).append("\n");
    sb.append("    vdpUrl: ").append(toIndentedString(vdpUrl)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    isCertified: ").append(toIndentedString(isCertified)).append("\n");
    sb.append("    dom: ").append(toIndentedString(dom)).append("\n");
    sb.append("    dom180: ").append(toIndentedString(dom180)).append("\n");
    sb.append("    domActive: ").append(toIndentedString(domActive)).append("\n");
    sb.append("    sellerType: ").append(toIndentedString(sellerType)).append("\n");
    sb.append("    lastSeenAt: ").append(toIndentedString(lastSeenAt)).append("\n");
    sb.append("    lastSeenAtDate: ").append(toIndentedString(lastSeenAtDate)).append("\n");
    sb.append("    build: ").append(toIndentedString(build)).append("\n");
    sb.append("    media: ").append(toIndentedString(media)).append("\n");
    sb.append("    extra: ").append(toIndentedString(extra)).append("\n");
    sb.append("    dealer: ").append(toIndentedString(dealer)).append("\n");
    sb.append("    carLocation: ").append(toIndentedString(carLocation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

