/*
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package marketcheck.cars.api..client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * PlotPoint
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-03-09T10:14:35.317+05:30")
public class PlotPoint {
  @SerializedName("price")
  private BigDecimal price = null;

  @SerializedName("miles")
  private BigDecimal miles = null;

  @SerializedName("vin")
  private String vin = null;

  @SerializedName("msrp")
  private BigDecimal msrp = null;

  @SerializedName("dom")
  private BigDecimal dom = null;

  @SerializedName("seller_name")
  private String sellerName = null;

  @SerializedName("id")
  private String id = null;

  public PlotPoint price(BigDecimal price) {
    this.price = price;
    return this;
  }

   /**
   * Price
   * @return price
  **/
  @ApiModelProperty(value = "Price")
  public BigDecimal getPrice() {
    return price;
  }

  public void setPrice(BigDecimal price) {
    this.price = price;
  }

  public PlotPoint miles(BigDecimal miles) {
    this.miles = miles;
    return this;
  }

   /**
   * Miles
   * @return miles
  **/
  @ApiModelProperty(value = "Miles")
  public BigDecimal getMiles() {
    return miles;
  }

  public void setMiles(BigDecimal miles) {
    this.miles = miles;
  }

  public PlotPoint vin(String vin) {
    this.vin = vin;
    return this;
  }

   /**
   * Vin
   * @return vin
  **/
  @ApiModelProperty(value = "Vin")
  public String getVin() {
    return vin;
  }

  public void setVin(String vin) {
    this.vin = vin;
  }

  public PlotPoint msrp(BigDecimal msrp) {
    this.msrp = msrp;
    return this;
  }

   /**
   * Msrp
   * @return msrp
  **/
  @ApiModelProperty(value = "Msrp")
  public BigDecimal getMsrp() {
    return msrp;
  }

  public void setMsrp(BigDecimal msrp) {
    this.msrp = msrp;
  }

  public PlotPoint dom(BigDecimal dom) {
    this.dom = dom;
    return this;
  }

   /**
   * DOM
   * @return dom
  **/
  @ApiModelProperty(value = "DOM")
  public BigDecimal getDom() {
    return dom;
  }

  public void setDom(BigDecimal dom) {
    this.dom = dom;
  }

  public PlotPoint sellerName(String sellerName) {
    this.sellerName = sellerName;
    return this;
  }

   /**
   * Seller name
   * @return sellerName
  **/
  @ApiModelProperty(value = "Seller name")
  public String getSellerName() {
    return sellerName;
  }

  public void setSellerName(String sellerName) {
    this.sellerName = sellerName;
  }

  public PlotPoint id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Listing id
   * @return id
  **/
  @ApiModelProperty(value = "Listing id")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlotPoint plotPoint = (PlotPoint) o;
    return Objects.equals(this.price, plotPoint.price) &&
        Objects.equals(this.miles, plotPoint.miles) &&
        Objects.equals(this.vin, plotPoint.vin) &&
        Objects.equals(this.msrp, plotPoint.msrp) &&
        Objects.equals(this.dom, plotPoint.dom) &&
        Objects.equals(this.sellerName, plotPoint.sellerName) &&
        Objects.equals(this.id, plotPoint.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(price, miles, vin, msrp, dom, sellerName, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlotPoint {\n");
    
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    miles: ").append(toIndentedString(miles)).append("\n");
    sb.append("    vin: ").append(toIndentedString(vin)).append("\n");
    sb.append("    msrp: ").append(toIndentedString(msrp)).append("\n");
    sb.append("    dom: ").append(toIndentedString(dom)).append("\n");
    sb.append("    sellerName: ").append(toIndentedString(sellerName)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

