/*
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package marketcheck.cars.api..client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * Describes the Safety Ratings of current listing
 */
@ApiModel(description = "Describes the Safety Ratings of current listing")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-03-09T10:14:35.317+05:30")
public class SafetyRating {
  @SerializedName("overall_rating")
  private BigDecimal overallRating = null;

  @SerializedName("roll_over_rating")
  private BigDecimal rollOverRating = null;

  @SerializedName("driver_side_rating")
  private BigDecimal driverSideRating = null;

  @SerializedName("driver_front_rating")
  private BigDecimal driverFrontRating = null;

  @SerializedName("passenger_front_rating")
  private BigDecimal passengerFrontRating = null;

  public SafetyRating overallRating(BigDecimal overallRating) {
    this.overallRating = overallRating;
    return this;
  }

   /**
   * Overall rating of the Listing on scale 1-5
   * @return overallRating
  **/
  @ApiModelProperty(value = "Overall rating of the Listing on scale 1-5")
  public BigDecimal getOverallRating() {
    return overallRating;
  }

  public void setOverallRating(BigDecimal overallRating) {
    this.overallRating = overallRating;
  }

  public SafetyRating rollOverRating(BigDecimal rollOverRating) {
    this.rollOverRating = rollOverRating;
    return this;
  }

   /**
   * Roll Over rating of the Listing on scale 1-5
   * @return rollOverRating
  **/
  @ApiModelProperty(value = "Roll Over rating of the Listing on scale 1-5")
  public BigDecimal getRollOverRating() {
    return rollOverRating;
  }

  public void setRollOverRating(BigDecimal rollOverRating) {
    this.rollOverRating = rollOverRating;
  }

  public SafetyRating driverSideRating(BigDecimal driverSideRating) {
    this.driverSideRating = driverSideRating;
    return this;
  }

   /**
   * Driver Side rating of the Listing on scale 1-5
   * @return driverSideRating
  **/
  @ApiModelProperty(value = "Driver Side rating of the Listing on scale 1-5")
  public BigDecimal getDriverSideRating() {
    return driverSideRating;
  }

  public void setDriverSideRating(BigDecimal driverSideRating) {
    this.driverSideRating = driverSideRating;
  }

  public SafetyRating driverFrontRating(BigDecimal driverFrontRating) {
    this.driverFrontRating = driverFrontRating;
    return this;
  }

   /**
   * Driver front rating of the Listing on scale 1-5
   * @return driverFrontRating
  **/
  @ApiModelProperty(value = "Driver front rating of the Listing on scale 1-5")
  public BigDecimal getDriverFrontRating() {
    return driverFrontRating;
  }

  public void setDriverFrontRating(BigDecimal driverFrontRating) {
    this.driverFrontRating = driverFrontRating;
  }

  public SafetyRating passengerFrontRating(BigDecimal passengerFrontRating) {
    this.passengerFrontRating = passengerFrontRating;
    return this;
  }

   /**
   * Passenger front rating of the Listing on scale 1-5
   * @return passengerFrontRating
  **/
  @ApiModelProperty(value = "Passenger front rating of the Listing on scale 1-5")
  public BigDecimal getPassengerFrontRating() {
    return passengerFrontRating;
  }

  public void setPassengerFrontRating(BigDecimal passengerFrontRating) {
    this.passengerFrontRating = passengerFrontRating;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SafetyRating safetyRating = (SafetyRating) o;
    return Objects.equals(this.overallRating, safetyRating.overallRating) &&
        Objects.equals(this.rollOverRating, safetyRating.rollOverRating) &&
        Objects.equals(this.driverSideRating, safetyRating.driverSideRating) &&
        Objects.equals(this.driverFrontRating, safetyRating.driverFrontRating) &&
        Objects.equals(this.passengerFrontRating, safetyRating.passengerFrontRating);
  }

  @Override
  public int hashCode() {
    return Objects.hash(overallRating, rollOverRating, driverSideRating, driverFrontRating, passengerFrontRating);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SafetyRating {\n");
    
    sb.append("    overallRating: ").append(toIndentedString(overallRating)).append("\n");
    sb.append("    rollOverRating: ").append(toIndentedString(rollOverRating)).append("\n");
    sb.append("    driverSideRating: ").append(toIndentedString(driverSideRating)).append("\n");
    sb.append("    driverFrontRating: ").append(toIndentedString(driverFrontRating)).append("\n");
    sb.append("    passengerFrontRating: ").append(toIndentedString(passengerFrontRating)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

