/*
 * Marketcheck Cars API
 * <b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package marketcheck.cars.api..client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * TrendPoint
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-03-09T10:14:35.317+05:30")
public class TrendPoint {
  @SerializedName("price")
  private BigDecimal price = null;

  @SerializedName("miles")
  private BigDecimal miles = null;

  @SerializedName("dom")
  private BigDecimal dom = null;

  @SerializedName("units")
  private BigDecimal units = null;

  @SerializedName("msrp")
  private BigDecimal msrp = null;

  public TrendPoint price(BigDecimal price) {
    this.price = price;
    return this;
  }

   /**
   * Price
   * @return price
  **/
  @ApiModelProperty(value = "Price")
  public BigDecimal getPrice() {
    return price;
  }

  public void setPrice(BigDecimal price) {
    this.price = price;
  }

  public TrendPoint miles(BigDecimal miles) {
    this.miles = miles;
    return this;
  }

   /**
   * Miles
   * @return miles
  **/
  @ApiModelProperty(value = "Miles")
  public BigDecimal getMiles() {
    return miles;
  }

  public void setMiles(BigDecimal miles) {
    this.miles = miles;
  }

  public TrendPoint dom(BigDecimal dom) {
    this.dom = dom;
    return this;
  }

   /**
   * Days on Market
   * @return dom
  **/
  @ApiModelProperty(value = "Days on Market")
  public BigDecimal getDom() {
    return dom;
  }

  public void setDom(BigDecimal dom) {
    this.dom = dom;
  }

  public TrendPoint units(BigDecimal units) {
    this.units = units;
    return this;
  }

   /**
   * Units
   * @return units
  **/
  @ApiModelProperty(value = "Units")
  public BigDecimal getUnits() {
    return units;
  }

  public void setUnits(BigDecimal units) {
    this.units = units;
  }

  public TrendPoint msrp(BigDecimal msrp) {
    this.msrp = msrp;
    return this;
  }

   /**
   * MSRP
   * @return msrp
  **/
  @ApiModelProperty(value = "MSRP")
  public BigDecimal getMsrp() {
    return msrp;
  }

  public void setMsrp(BigDecimal msrp) {
    this.msrp = msrp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrendPoint trendPoint = (TrendPoint) o;
    return Objects.equals(this.price, trendPoint.price) &&
        Objects.equals(this.miles, trendPoint.miles) &&
        Objects.equals(this.dom, trendPoint.dom) &&
        Objects.equals(this.units, trendPoint.units) &&
        Objects.equals(this.msrp, trendPoint.msrp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(price, miles, dom, units, msrp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrendPoint {\n");
    
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    miles: ").append(toIndentedString(miles)).append("\n");
    sb.append("    dom: ").append(toIndentedString(dom)).append("\n");
    sb.append("    units: ").append(toIndentedString(units)).append("\n");
    sb.append("    msrp: ").append(toIndentedString(msrp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

